from unicodedata import name
from flask import current_app as app
'''

CREATE TABLE IF NOT EXISTS public.inventory
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name varchar(255) NOT NULL,
    uid integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (id, uid)
);

'''

class Inventory:
    def __init__(self, id, uid, name, quantity=0):
        self.id = id
        self.uid = uid
        self.quantity = quantity
        self.name = name

    @staticmethod
    def get(uid):
        rows = app.db.execute('''
SELECT id, name, uid, quantity
FROM Inventory
WHERE id = :id AND uid = :uid
''',
                             uid=uid)
        return Inventory(*(rows[0])) if rows else None

    @staticmethod
    def remove_product(id, uid, rnum):
        rows = app.db.execute('''
UPDATE Inventory
SET quantity = quantity + :rnum
WHERE id = :id AND uid = :uid
RETURNING quantity
        ''', id=id, uid=uid, rnum=rnum)
        quantity = rows[0][0]
        return quantity

    @staticmethod
    def add_product(uid, name):
        rows = app.db.execute('''
SELECT id, uid, name
FROM Inventory
WHERE uid = :uid AND name = :name
''',
                            uid=uid, name=name
                            )
        if not rows:
            rows = app.db.execute('''
INSERT INTO Inventory(name, uid, quantity)
VALUES(:name, :uid, :quantity)
RETURNING id
            ''', name=name, uid=uid, quantity=1)
            id = rows[0][0]
            return Inventory.get(id)
        return Inventory(*(rows[0])) if rows else None